### ISSUE TITLE
Game don't start with minetest 5.4.1

### ISSUE THREAD

**Issue by AFCMS** [sfence/clothing#4] opened 2021-08-13 10:53 UTC
The game stay blocked then loading the mod

(using also `appliance` mod)

**Comment by sfence** [comment] 2021-08-15 15:43
Thanks for reporting.

I need more information to replicate the problem and solve it.

Are you able to send me a list of mods, you are using when this problem is happening to you? (Is available in world file world.mt)
And maybe operation system (Linux, win, mac) where you are trying it?

**Comment by AFCMS** [comment] 2021-08-15 20:10
Looks strange... I tested with ONLY mentioned mods, and it works.

With this world.mt, this don't work (most activated mods are very commun):
```
enable_damage = true
gameid = minetest
world_name = tshot
backend = sqlite3
player_backend = sqlite3
auth_backend = sqlite3
creative_mode = true
load_mod_pala_looting = false
load_mod_pala_dynamite = false
load_mod_pala_fakewater = false
load_mod_mcl_build_limit = false
load_mod_technic_cnc = false
load_mod_pala_obsidian = false
load_mod_extranodes = false
load_mod_concrete = false
load_mod_technic = false
load_mod_technic_worldgen = false
load_mod_farming_flood = true
load_mod_pala_furnace = false
load_mod_pala_job = false
load_mod_pala_tools = false
load_mod_pala_sticks = false
load_mod_technic_chests = false
load_mod_pala_golem = false
load_mod_pala_spikes = false
load_mod_pala_backpack = false
load_mod_pala_luckyblock = false
load_mod_pala_armor = false
load_mod_pala_paladium = false
load_mod_pala_legendary = false
load_mod_i3 = true
load_mod_pala_machines = false
load_mod_wrench = false
load_mod_pala_food = false
load_mod_pala_mapgen = false
load_mod_pala_decoblock = false
load_mod_pala_spawner = false
server_announce = false
load_mod_rangedweapons = true
load_mod_water_life = true
load_mod_hangglider = true
load_mod_draconis = true
load_mod_3d_armor_ui = true
load_mod_shields = true
load_mod_wildlife = true
load_mod_3d_armor = true
load_mod_mobkit = true
load_mod_sailing_kit = true
load_mod_wieldview = true
load_mod_3d_armor_stand = true
load_mod_3d_armor_ip = true
load_mod_3d_armor_sfinv = true
load_mod_mob_core = true
load_mod_wield3d = true
load_mod_3d_armor_flyswim = true
load_mod_microexpansion = false
load_mod_pala_server = false
load_mod_pala_grade = false
load_mod_mcl_welcome_hud = false
load_mod_mesecons_materials = true
load_mod_mesecons_stickyblocks = true
load_mod_mesecons_detector = true
load_mod_mesecons_powerplant = true
load_mod_mesecons_blinkyplant = true
load_mod_mesecons_walllever = true
load_mod_meshport = true
load_mod_mesecons_lamp = true
load_mod_mesecons_hydroturbine = true
load_mod_mesecons_movestones = true
load_mod_mesecons_delayer = true
load_mod_mesecons_lightstone = true
load_mod_mesecons_fpga = true
load_mod_mesecons_extrawires = true
load_mod_mesecons_gates = true
load_mod_mesecons_mvps = true
load_mod_mesecons = true
load_mod_worldedit_brush = true
load_mod_mesecons_receiver = true
load_mod_worldedit_commands = true
load_mod_mc_economy = false
load_mod_drawers = false
load_mod_worldedit_shortcommands = true
load_mod_mesecons_switch = true
load_mod_mesecons_button = true
load_mod_mesecons_alias = true
load_mod_worldedit = true
load_mod_mesecons_random = true
load_mod_mesecons_microcontroller = true
load_mod_worldedit_gui = true
load_mod_blabla = false
load_mod_mesecons_insulated = true
load_mod_mesecons_torch = true
load_mod_mc_faction = false
load_mod_mcl_uhc = false
load_mod_mesecons_luacontroller = true
load_mod_mesecons_solarpanel = true
load_mod_mesecons_pistons = true
load_mod_mesecons_noteblock = true
load_mod_mesecons_wires = true
load_mod_mesecons_doors = true
load_mod_mesecons_pressureplates = true
load_mod_mesecons_commandblock = true
load_mod_commoditymarket = true
load_mod_global_market = true
load_mod_mtfs = true
load_mod_trike = true
load_mod_biofuel = true
load_mod_rocket = true
load_mod_pala_storage = false
load_mod_hidroplane = true
load_mod_other_worlds = false
load_mod_motorboat = true
load_mod_mcl_speedrun = false
load_mod_stairs = false
load_mod_simple_protection = false
load_mod_skywars = false
load_mod_mtsedit = false
load_mod_kitpvp = false
load_mod_bedwars = false
load_mod_mcl_falling_anvils = false
load_mod_burger_skywars = false
load_mod_multihome = false
load_mod_nautilus = true
load_mod_bedwars_wip = false
load_mod_supercharger = true
load_mod_vehicles = true
load_mod_pala_craftitems = false
load_mod_complex_commands = false
load_mod_mesecons_onlinedetector = true
load_mod_mcl_spyglass = false
load_mod_mcl_nether_gold = false
load_mod_mcl_copper = false
load_mod_extra_mobs = false
load_mod_ttnt = false
load_mod_mt2d = false
load_mod_fun_survival = false
load_mod_tower_defense = false
load_mod_skybox = false
load_mod_db_manager = false
load_mod_cipher_3122 = false
load_mod_mcl_deepslate = false
load_mod_pala_test = false
load_mod_mcl_multitool = false
load_mod_dupe_inv = false
load_mod_pala_core = false
load_mod_war = false
load_mod_mcl_raw_ores = false
load_mod_mcl_testingcolors = false
load_mod_fireworkz = true
load_mod_digiscreen = true
load_mod_led_marquee = true
load_mod_digilines = true
load_mod_mesecons_carts = true
load_mod_spacecannon = false
load_mod_digiterms = false
load_mod_digistuff = true
load_mod_mesecons_soundblock = true
load_mod_digibuilder = true
load_mod_ham_radio = false
load_mod_pipeworks = true
load_mod_basic_materials = true
load_mod_mcl_chalenges = false
load_mod_skinsdb = true
load_mod_awards = true
load_mod_clothing = false
load_mod_appliances = false
load_mod_lucky_block = true
```
System: Ubuntu 20.04

**Comment by sfence** [comment] 2021-08-16 06:19
It looks like some collision between i3 and clothing mod.

At the moment, you should be able to use all mods, including clothing if you use unified_inventory instead of i3 mod.

**Comment by AFCMS** [comment] 2021-08-16 07:16
i3 > unified_inventory :cry: 
Can this problem be fixed?

**Comment by sfence** [comment] 2021-08-16 07:51
Probably yes, I have already find the i3 commit from which this problem occurs.

The problem is probably in calling of i3.register_craft function.
If you are playing creative world, you can too use i3 and clothing with disabled crafting registration (clothing_enable_craft = false) at the moment.

**Comment by sfence** [comment] 2021-08-16 07:59
But, I should warn you, that i3 mod doesn't include clothing support at the moment.

**This mod has limited support for i3 inventory mod. If you want to use clothing with i3 mod, you should ask author of i3 mod to add support for it (like for skinsdb). It cannot be solved in clothing mod due to problem with cycle dependency, because appliances mod depends on i3 mod and i3 mod depend on skinsdb mod which depends on clothing mod which depends on appliances mod.**

**Comment by sfence** [comment] 2021-08-16 08:42
Ok. At the moment, after the update of appliances mod, the problem with infinite loading should be fixed.

It looks like there is some problem with the update of contentDB database, so it can take a while until the update will be available.

**Closed as completed** 2021-08-29 16:51 UTC
